version: '3'
services:
  api:
    image: openrecord/turntable
    build:
      context: .
      dockerfile: ./docker/turntable/Dockerfile
    ports:
      - 3099:3099
    volumes:
      - .:/app
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    volumes:
      - ./docker/mysql/mount:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306