# docs.serverless.com

service: openrecord-turntable

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1

functions:
  proxy:
    handler: src/app/functions.proxy
    events:
      - http:
          method: ANY
          path: /
          cors: true
      - http:
          method: ANY
          path: /{proxy+}
          cors: true
package:
  exclude:
    - config/**/*local*.yml
    - src/database/*
    - src/test/*
    - docker/*
    - .idea/**
    - .circleci/**
    - .*

plugins:
  - serverless-offline